name = "jcourse-backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
APP_ENV = "production"

[[d1_databases]]
binding = "DB"
database_name = "jcourse-db"
database_id = "ced26cfd-a3a7-4b06-ac3f-587c9c939c1c"

[[kv_namespaces]]
binding = "COURSE_SEARCH_INDEX"
id = "2a9f78e1e4e84bdfa2d7285f85b5eff0"

[env.dev]
name = "jcourse-backend-dev"

[env.dev.vars]
APP_ENV = "dev"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "jcourse-db"
database_id = "ced26cfd-a3a7-4b06-ac3f-587c9c939c1c"

[[env.dev.kv_namespaces]]
binding = "COURSE_SEARCH_INDEX"
id = "e5079669bf8f4bdeac218dcfa88733b9"

# 环境变量需要通过 wrangler secret 设置:
# wrangler secret put CAPTCHA_SITEVERIFY_URL
# wrangler secret put ADMIN_SECRET
# wrangler secret put ONESYSTEM_COOKIE
# wrangler secret put TURNSTILE_SECRET_KEY
# （可选）wrangler secret put TURNSTILE_SITEVERIFY_URL
